spring:
  application:
    name: user-journal
  data:
    mongodb:
      database: journaldb
      username: nraboy
      password: password1234
      host: localhost
      port: 27017
      authentication-database: journaldb
      auto-index-creation: true
